name: Release to NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    name: Pack and Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm install --ignore-scripts true
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
